# This file was generated by GoReleaser. DO NOT EDIT.
class Merlin < Formula
  desc "merlin --help"
  homepage "http://docs.codefresh.io"
  url "https://github.com/codefresh-io/merlin/releases/download/v1.11.1/merlin_1.11.1_Darwin_x86_64.tar.gz"
  version "1.11.1"
  sha256 "254ddc9a1a9d2daaeee64e0a8356b5d4e28579a99965491be3bd87ed8ca013b3"

  def install
    bin.install "merlin"
  end
end
