# This file was generated by GoReleaser. DO NOT EDIT.
class Merlin < Formula
  desc "merlin --help"
  homepage "http://docs.codefresh.io"
  url "https://github.com/codefresh-io/merlin/releases/download/v1.12.0/merlin_1.12.0_Darwin_x86_64.tar.gz"
  version "1.12.0"
  sha256 "55cca7b108b3769bab0fcdae5389f66db3ab0cb299ca6d08eeb1e4c34bc3f163"

  def install
    bin.install "merlin"
  end
end
